FROM node:20.10

WORKDIR /usr/src/app

EXPOSE 3000
RUN apt update && apt install -y wget


ENV DOCKERIZE_VERSION v0.7.0

RUN wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
    && apt-get autoremove -yqq --purge wget && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["dockerize", "-wait", "tcp://mysql:3306", "-timeout", "20s", "docker-entrypoint.sh"]

CMD [ "npm", "start" ]