version: "3"


services:
  app:
    container_name: app
    build:
      context: node
      dockerfile: Dockerfile.prod
    networks:
      - nodedb-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    expose:
      - 3000
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: "--innodb-use-native-aio=0"
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

    networks:
      - nodedb-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"

    networks:
      - nodedb-network



networks:
  nodedb-network:
    driver: bridge

